export const APP_ACTIONS = {
  FETCH_FOLLOWERS: "app/FETCH_FOLLOWERS",
  SET_LOGIN_ERROR: "app/SET_LOGIN_ERROR",
  SET_USERNAME: "app/SET_USERNAME",
  SET_EVENTS: "app/SET_EVENTS",
  TOGGLE_FORK_EVENTS: "app/TOGGLE_FORK_EVENTS",
  TOGGLE_PULL_REQUEST_EVENTS: "app/TOGGLE_PULL_REQUEST_EVENTS",
  USER_LOGIN: "app/USER_LOGIN",
  USER_LOGOUT: "app/USER_LOGOUT"
};
